package pojos;
// Generated Oct 29, 2020 7:23:50 PM by Hibernate Tools 4.3.1



/**
 * Players generated by hbm2java
 */
public class Players  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String age;
     private String country;
     private String position;

    public Players() {
    }

    public Players(String name, String age, String country, String position) {
       this.name = name;
       this.age = age;
       this.country = country;
       this.position = position;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    @Override
    public String toString() {
        return "Имя: " + name + ", Возраст: " + age + ", Страна: " + country + ", Позиция: " + position;
    }


}


